# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Moon Phases' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moon Phases
  pod 'Nimble'

  target 'Moon PhasesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moon PhasesUITests' do
    # Pods for testing
  end

end
